_target_: src.dataset_module.ice_text_image_iclm_ds.ICETextImageICLMDataset


clip_processor_name: "openai/clip-vit-base-patch32"
index_set_length: ${dataset.train_ds_len}


image_field: ${task.image_field}
text_field: ${task.ice_text_feature_field}