coco_root: ${oc.env:COCO_PATH}
coco2017_root: ${dataset.coco_root}/mscoco2017
version: 2017
train_ds_len: 118287
train_coco_dataset_root: ${dataset.coco2017_root}/train2017
train_coco_annotation_file: ${dataset.coco2017_root}/annotations/captions_train2017.json
val_coco_dataset_root: ${dataset.coco2017_root}/val2017
val_coco_annotation_file: ${dataset.coco2017_root}/annotations/captions_val2017.json