coco_root: ${oc.env:COCO_PATH}
version: 2014
train_coco_dataset_root: ${dataset.coco_root}/train2014
train_coco_annotation_file: ${dataset.coco_root}/annotations/captions_train2014.json
val_coco_dataset_root: ${dataset.coco_root}/val2014
val_coco_annotation_file: ${dataset.coco_root}/annotations/captions_val2014.json