coco_root: ${oc.env:COCO_PATH}
coco2014_root: ${dataset.coco_root}/mscoco2014
version: 2014
karpathy_path: "yerevann/coco-karpathy"
train_coco_dataset_root: ${dataset.coco2014_root}/train2014
train_coco_annotation_file: ${dataset.coco2014_root}/annotations/captions_train2014.json
val_coco_dataset_root: ${dataset.coco2014_root}/val2014
val_coco_annotation_file: ${dataset.coco2014_root}/annotations/captions_val2014.json