version: local
name: vqav2
train_ds_len: 443757
train_path: ${oc.env:VQAV2_PATH}/vqav2_hf/vqav2_mscoco_train2014.json
val_path: ${oc.env:VQAV2_PATH}/vqav2_hf/vqav2_mscoco_val2014_subset.json
train_coco_dataset_root: ${oc.env:COCO_PATH}/mscoco2014/train2014
val_coco_dataset_root: ${oc.env:COCO_PATH}/mscoco2014/val2014

# use for eval
val_ques_path: ${oc.env:VQAV2_PATH}/v2_OpenEnded_mscoco_val2014_questions.json
val_ann_path: ${oc.env:VQAV2_PATH}/v2_mscoco_val2014_annotations.json