version: local
name: vqav2
train_ds_len: 443757
train_ann_path: ${oc.env:VQAV2_PATH}/v2_mscoco_train2014_annotations.json
val_ann_path: ${oc.env:VQAV2_PATH}/v2_mscoco_val2014_annotations_subdata.json
train_coco_dataset_root: ${oc.env:COCO_PATH}/mscoco2014/train2014
