
hf_root: OpenFlamingo-9B-deprecated
flamingo_checkpoint_dir: ${oc.env:CHECKPOINT_PATH}/${flamingo.hf_root}/
lang_encoder_path: huggyllama/llama-7b
tokenizer_path: ${flamingo.lang_encoder_path}
cross_attn_every_n_layers: 4
load_from_local: true
