# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - flamingo: flamingo_9B
  - dataset: coco2017
  - task: caption


# get candidate_set args
random_sample_candidate_set: false
candidate_set_num: 128

# recall args
sim_method: "text"
sim_model_type: "openai/clip-vit-large-patch14"
candidate_set_encode_bs: 64


# generation args:
beam_size: 5
few_shot_num: 2
batch_size: 32
device: "cuda"
precision: bf16
sample_num: 10000

# Others
result_dir: "./result"
gpu_ids: [0]
# load several models at the same time will cost large memory.
# use sleep to load one by one.
sleep_time: 90


only_y_loss: true
split_token: "Output:"

# hydra
hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${task.task_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/multirun/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}