defaults:
  - _self_
  - dataset: coco2017
  - flamingo: flamingo_9B
  - train: idx_base

use_karpathy_split: false

overwrite_metainfo: false
precision: bf16
device: cuda
test_data_num: -1
other_save_field: ['single_caption', 'captions', 'image_id']
inference_bs: 32
gen_args:
  max_new_tokens: 20
  num_beams: 3
  length_penalty: 0.0
  min_new_tokens: 0

eos_token_id: 118287
bos_token_id: 118288
query_token_id: 118289


result_dir: "./result"
ex_name: "default"
iclm_path: "result/model_cpk/idx_base_iclm_2shot_with_imgToken_loss/last-val_loss:5.5326.pth"



test_zero_shot: false
test_topk_caption: false
test_random: false
test_iclm: false
test_i2t: false
test_i2i: false


mmtopk_clip_name: openai/clip-vit-large-patch14
shot_num_list: [2, 4, 8]

hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${ex_name}/${now:%Y-%m-%d_%H-%M-%S}
