defaults:
  - _self_
  - dataset: coco2017
  - flamingo: flamingo_9B
  - train: query_img_ice_text
  - task: caption


# for fast version:
num_workers: 16
num_proc: 16
preprocessor_bs: 100


# generation config
precision: bf16
device: cuda
index_data_num: -1
test_data_num: -1

inference_bs: 4

# MMTopK config:
mmtopk_clip_name: openai/clip-vit-base-patch32

# iclm config:
iclm_path: ???
eos_token_id: ${dataset.train_ds_len}

# Others
result_dir: "./result"
ex_name: "debug"
shot_num_list: [1, 2, 3, 4, 5, 6, 8]
test_zero_shot: false
test_random: false
test_iclm: false
test_t2t: false
test_i2t: false
test_i2i: false

hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${ex_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${ex_name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.override_dirname}