defaults:
  - _self_
  - dataset: coco2017
  - flamingo: flamingo_9B
  - train: idx_base

# generation config
overwrite_metainfo: false
precision: bf16
device: cuda
test_data_num: -1
other_save_field: ['single_caption', 'captions', 'image_id']
inference_bs: 1
gen_args:
  max_new_tokens: 20
  num_beams: 3
  length_penalty: 0.0
  min_new_tokens: 0

# MMTopK config:
mmtopk_clip_name: openai/clip-vit-large-patch14

# iclm config:
iclm_path: "result/model_cpk/idx_base_iclm_2shot_with_imgToken_loss/last-val_loss:5.5326.pth"
eos_token_id: 118287
bos_token_id: 118288
query_token_id: 118289

# Others
result_dir: "./result"
ex_name: "debug"
shot_num_list: [1, 2]
test_zero_shot: false
test_random: false
test_iclm: true
test_t2t: false
test_i2t: false
test_i2i: false

hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${ex_name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/hydra_output/multirun/${hydra.job.name}/${ex_name}/${now:%Y-%m-%d_%H-%M-%S}