# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - train: idx_base
  - dataset: coco2017
  - task: caption


# data args
data_files: OpenFlamingo-9B-vitl-mpt7b-coco-caption-beam_size:16-few_shot:2-query_top_k:64.json

# train args:
epochs: 50
train_ratio: 0.9
lr: 1e-4
batch_size: 64
num_workers: 8
warm_up_ratio: 0.05
val_step: 200

# Others
result_dir: "./result"
ex_name: "default"
device: "cuda"
device_num: 1
precision: 16
seed: 42


hydra:
  run:
    dir: ${result_dir}/hydra_output/${hydra.job.name}/${ex_name}/${now:%Y-%m-%d_%H-%M-%S}
