# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_

  - train/ice_seq_idx_ds: clip_encode_base_ds
  - train/iclm_model: clip_encode_base_iclm
  - dataset: coco_dataset


# data args
data_files: open_flamingo-coco-caption-beam_size:8-few_shot:4-query_top_k:50_by_train_ds.json

# train args:
epochs: 50
train_ratio: 0.9
lr: 1e-4
batch_size: 64
num_workers: 8
warm_up_ratio: 0.05


# Others
result_dir: "./result"
ex_name: "default"
device: "cuda"
device_num: 4
precision: 16
seed: 42



hydra:
  hydra_logging:
    log_dir: ${result_dir}/hydra_logs